# Generated by Django 4.2.20 on 2026-04-25 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('info', 'お知らせ'), ('maintenance', 'メンテナンス'), ('feature', '新機能'), ('bugfix', 'バグ修正'), ('warning', '警告')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開'), ('archived', '終了')], default='draft', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('feature', '機能追加'), ('improve', '改善'), ('bugfix', 'バグ修正'), ('security', 'セキュリティ'), ('infra', 'インフラ'), ('breaking', '破壊的変更')], default='feature', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
