# Generated by Django 3.0.7 on 2026-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='account_type',
            field=models.CharField(choices=[('taxable', '特定口座'), ('nisa_growth', '新NISA成長投資枠'), ('nisa_accumulation', '新NISAつみたて投資枠')], default='taxable', max_length=20),
        ),
    ]
