# Generated by Django 4.2.20 on 2026-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='high_alert_status',
            field=models.CharField(choices=[('none', 'なし'), ('alert_10', '10%以上下落'), ('alert_20', '20%以上下落')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='high_price_1y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='high_price_1y_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
