# Generated by Django 3.0.7 on 2026-03-22 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('stock', models.CharField(blank=True, max_length=32)),
                ('dividend', models.FloatField(blank=True, default=None, null=True)),
                ('dividend_rank', models.IntegerField(blank=True, default=None, null=True)),
                ('dividend_update', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('psr', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='api_market.Company')),
            ],
            options={
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='IndicatorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per', models.FloatField(blank=True, null=True)),
                ('psr', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('collected_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_histories', to='api_market.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(blank=True, default=0, max_length=32, null=True, verbose_name='売上高')),
                ('operating_margin', models.FloatField(blank=True, null=True, verbose_name='営業利益率')),
                ('eps', models.FloatField(blank=True, null=True, verbose_name='EPS')),
                ('equity_ratio', models.FloatField(blank=True, null=True, verbose_name='自己資本比率')),
                ('operating_cash_flow', models.BigIntegerField(blank=True, null=True, verbose_name='営業CF')),
                ('cash_and_equivalents', models.BigIntegerField(blank=True, null=True, verbose_name='現金等')),
                ('dividend_per_share', models.BigIntegerField(blank=True, null=True, verbose_name='1株配当')),
                ('payout_ratio', models.FloatField(blank=True, null=True, verbose_name='配当性向')),
                ('fiscal_year', models.CharField(max_length=16, verbose_name='会計年度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api_market.Company')),
            ],
            options={
                'db_table': 'financials',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='company_code_2351f9_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorhistory',
            index=models.Index(fields=['company', 'collected_at'], name='api_market__company_fb882a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorhistory',
            index=models.Index(fields=['collected_at'], name='api_market__collect_f06249_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatorhistory',
            constraint=models.UniqueConstraint(fields=('company', 'collected_at'), name='unique_company_date'),
        ),
        migrations.AddIndex(
            model_name='financial',
            index=models.Index(fields=['company', 'fiscal_year'], name='financials_company_0bca16_idx'),
        ),
        migrations.AddConstraint(
            model_name='financial',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_year'), name='unique_company_fiscal_year'),
        ),
    ]
