# Generated by Django 4.2.20 on 2026-05-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_market', '0002_alter_financial_id_alter_indicatorhistory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('business', models.TextField(blank=True, default='')),
                ('feature', models.TextField(blank=True, default='')),
                ('risk', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api_market.company')),
            ],
        ),
    ]
