# Generated by Django 4.2.20 on 2026-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_market', '0003_companydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
