# Generated by Django 4.2.20 on 2026-05-09 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_market', '0004_companydetail_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('years_analyzed', models.IntegerField(default=0)),
                ('sales_growth', models.BooleanField(blank=True, null=True)),
                ('sales_stable', models.BooleanField(blank=True, null=True)),
                ('operating_margin_ok', models.BooleanField(blank=True, null=True)),
                ('operating_margin_10', models.BooleanField(blank=True, null=True)),
                ('operating_margin_val', models.FloatField(blank=True, null=True)),
                ('eps_no_negative', models.BooleanField(blank=True, null=True)),
                ('eps_growth', models.BooleanField(blank=True, null=True)),
                ('eps_val', models.FloatField(blank=True, null=True)),
                ('equity_ratio_40', models.BooleanField(blank=True, null=True)),
                ('equity_ratio_60', models.BooleanField(blank=True, null=True)),
                ('equity_ratio_80', models.BooleanField(blank=True, null=True)),
                ('equity_ratio_val', models.FloatField(blank=True, null=True)),
                ('cf_positive', models.BooleanField(blank=True, null=True)),
                ('cf_growth', models.BooleanField(blank=True, null=True)),
                ('cf_val', models.BigIntegerField(blank=True, null=True)),
                ('cash_growth', models.BooleanField(blank=True, null=True)),
                ('cash_val', models.BigIntegerField(blank=True, null=True)),
                ('dividend_stable', models.BooleanField(blank=True, null=True)),
                ('dividend_growth', models.BooleanField(blank=True, null=True)),
                ('dividend_val', models.BigIntegerField(blank=True, null=True)),
                ('payout_ratio_ok', models.BooleanField(blank=True, null=True)),
                ('payout_ratio_high', models.BooleanField(blank=True, null=True)),
                ('payout_ratio_val', models.FloatField(blank=True, null=True)),
                ('latest_fiscal_year', models.CharField(blank=True, default='', max_length=16)),
                ('latest_sales', models.FloatField(blank=True, null=True)),
                ('latest_operating_margin', models.FloatField(blank=True, null=True)),
                ('latest_eps', models.FloatField(blank=True, null=True)),
                ('latest_equity_ratio', models.FloatField(blank=True, null=True)),
                ('latest_operating_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('latest_cash_and_equivalents', models.BigIntegerField(blank=True, null=True)),
                ('latest_dividend_per_share', models.BigIntegerField(blank=True, null=True)),
                ('latest_payout_ratio', models.FloatField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='api_market.company')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('total_count', models.IntegerField(default=0)),
                ('refreshed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-refreshed_at'],
            },
        ),
    ]
