# Generated by Django 3.0.7 on 2026-04-19 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('certification', '資格'), ('language', 'プログラミング言語'), ('framework', 'フレームワーク'), ('infrastructure', 'インフラ'), ('network', 'ネットワーク'), ('tool', 'ツール'), ('other', 'その他')], default='other', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='習熟度 1〜5（任意）', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api_profile.Profile')),
            ],
            options={
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('qiita', 'Qiita'), ('zenn', 'Zenn'), ('website', 'Webサイト'), ('other', 'その他')], default='other', max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api_profile.Profile')),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='api_profile.Profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
